<body style=max-width:80ch;margin:auto>
<h1 class="entry-title" style="margin-bottom:15px;">The case of the memory corruption from a coroutine that already finished</h1>  <!-- .entry-meta -->

<p>A customer was getting sporadic crashes in the following code fragment:</p>
<pre>class Widget : WidgetT&lt;Widget&gt;
{
public:
    winrt::IAsyncOperation&lt;bool&gt; InitializeAsync();

private:
    winrt::IAsyncAction GetHighScoreAsync();
    winrt::IAsyncAction GetNameAsync();
    winrt::IAsyncAction GetPictureAsync();

    winrt::hstring m_name{ L"(anonymous)" };
    winrt::SoftwareBitmap m_picture{ DefaultPicture() };
    std::optional&lt;int32_t&gt; m_highScore;
}

winrt::IAsyncAction Widget::GetHighScoreAsync()
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_highScore = co_await GetHighScoreFromServer();
}

winrt::IAsyncAction Widget::GetNameAsync()
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_name = co_await GetNameFromIdentityService();
}

winrt::IAsyncAction Widget::GetPictureAsync()
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_picture = co_await DecodePictureFromSettings();
}

winrt::IAsyncOperation&lt;bool&gt;
    Widget::InitializeAsync()
{
    auto lifetime = get_strong();

    try {
        // Get information in parallel. Faster!
        co_await winrt::when_all(
            GetHighScoreAsync(),
            GetNameAsync(),
            GetPictureAsyncAsync());
    } catch (...) {
        // Service is unavailable or something
        // else went wrong. Just proceed with whatever
        // worked.
    }

    ShowHighScore(m_highScore);
    BuildGreeting(m_name);
    CropPicture(m_picture);
}
</pre>
<p>The idea here is that they have an <code>Initialize­Async</code> coroutine function that wants to run a bunch of other coroutines to initialize stuff, and let those other coroutines run in parallel, since each one is doing something different. When all of the helper coroutines are done, we process the results. And if any of the helper coroutines fails, that’s okay. We just proceed with what we were able to get.</p>
<p>The crashes, though, indicated that <code>Build­Greeting</code> or <code>Crop­Picture</code> were crashing on their accesses to <code>m_name</code> and <code>m_picture</code>.</p>
<p>Let’s take a survey of how various programming languages allow you to wait for multiple asynchronous actions:</p>
<table border="1" cellpadding="3" cellspacing="0" class="cp3" style="border-collapse: collapse;">
<tbody>
<tr>
<th>Language</th>
<th>Method</th>
<th>Result</th>
<th>If any fail</th>
</tr>
<tr>
<td>C++</td>
<td>Concurrency::when_all</td>
<td><code>vector&lt;T&gt;</code></td>
<td>fail immediately</td>
</tr>
<tr>
<td>C++</td>
<td>winrt::when_all</td>
<td><code>void</code></td>
<td>fail immediately</td>
</tr>
<tr>
<td>C#</td>
<td>Task.WhenAll</td>
<td><code>T[]</code></td>
<td>wait for others</td>
</tr>
<tr>
<td>JavaScript</td>
<td>Promise.all</td>
<td><code>Array</code></td>
<td>fail immediately</td>
</tr>
<tr>
<td>JavaScript</td>
<td>Promise.allSettled</td>
<td><code>Array</code></td>
<td>wait for others</td>
</tr>
<tr>
<td>Python</td>
<td>asyncio.gather</td>
<td>List</td>
<td>fail immediately by default</td>
</tr>
<tr>
<td>Rust</td>
<td>join!</td>
<td>tuple</td>
<td>wait for others</td>
</tr>
<tr>
<td>Rust</td>
<td>try_join!</td>
<td>tuple</td>
<td>fail immediately</td>
</tr>
</tbody>
</table>
<p>Python’s <code>asynchio.gather</code> lets you choose whether a failed coroutine causes <code>gather</code> to fail immediately or to wait for others before failing. The default is to fail immediately.</p>
<p>This customer is using <code>winrt::when_all</code>, which (consults table) fails as soon as any coroutine fails. (Our <a href="/code/synthesizing-a-when-all-coroutine-from-pieces-you-already-have"> custom <code>when_all</code> has the same behavior</a>.)</p>
<p>What happened is that one of the coroutines, let’s say <code>Get­High­Score­Async</code> failed with an exception. That caused <code>winrt::when_all</code> to propagate the exception and abandon waiting on the other coroutines. The <code>Initialize­Async</code> method ignores the exception and then proceeds on the false assumption that all of the methods ran to complete (possibly with failure). When it tries to use the <code>m_name</code>, it races against the still-running <code>Get­Name­Async</code> method, causing the <code>L"(anonymous)"</code> string to be destructed at the same time it is being copied, which does not end well. A similar race occurs when <code>Crop­Picture</code> reads the <code>m_picture</code> while <code>Get­Picture­Async</code> is writing to it.</p>
<p>The simple solution here is to catch the exceptions in the coroutines so that they never produce a failure. That way, <code>winrt::when_all</code> never completes early.</p>
<pre>winrt::IAsyncAction Widget::GetHighScoreAsync() <span style="color: blue;">try</span>
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_highScore = co_await GetHighScoreFromServer();
} <span style="color: blue;">catch (...)
{
}</span>

winrt::IAsyncAction Widget::GetNameAsync() <span style="color: blue;">try</span>
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_name = co_await GetNameFromIdentityService();
} <span style="color: blue;">catch (...)
{
}</span>

winrt::IAsyncAction Widget::GetPictureAsync() <span style="color: blue;">try</span>
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_picture = co_await DecodePictureFromSettings();
} <span style="color: blue;">catch (...)
{
}</span>

winrt::IAsyncOperation&lt;bool&gt;
    Widget::InitializeAsync()
{
    auto lifetime = get_strong();

    <span style="color: red;">// <span style="text-decoration: line-through;">try {</span></span>
    // Get information in parallel. Faster!
    co_await winrt::when_all(
        GetHighScoreAsync(),
        GetNameAsync(),
        GetPictureAsyncAsync());
    <span style="color: red;">// <span style="text-decoration: line-through;">} catch (...) {</span></span>
    <span style="color: red;">// <span style="text-decoration: line-through;">    // Service is unavailable or something</span></span>
    <span style="color: red;">// <span style="text-decoration: line-through;">    // else went wrong. Just proceed with whatever</span></span>
    <span style="color: red;">// <span style="text-decoration: line-through;">    // worked.</span></span>
    <span style="color: red;">// <span style="text-decoration: line-through;">}</span></span>

    ShowHighScore(m_highScore);
    BuildGreeting(m_name);
    CropPicture(m_picture);
}
</pre>
<p>This code happens to use WIL, so there’s a helper macro for catching exceptions and logging them.</p>
<pre>winrt::IAsyncAction Widget::GetHighScoreAsync() <span style="color: blue;">try</span>
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_highScore = co_await GetHighScoreFromServer();
} <span style="color: blue;">CATCH_LOG()</span>

winrt::IAsyncAction Widget::GetNameAsync() <span style="color: blue;">try</span>
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_name = co_await GetNameFromIdentityService();
} <span style="color: blue;">CATCH_LOG()</span>

winrt::IAsyncAction Widget::GetPictureAsync() <span style="color: blue;">try</span>
{
    auto lifetime = get_strong();
    co_await winrt::resume_background();

    m_picture = co_await DecodePictureFromSettings();
} <span style="color: blue;">CATCH_LOG()</span>
</pre>


</body>