<body style=max-width:80ch;margin:auto>
<h1 class="entry-title" style="margin-bottom:15px;">Cancelling a Windows Runtime asynchronous operation, part 4: C++/CX with PPL, coroutine style with raw IAsyncAction and IAsyncOperation</h1>  <!-- .entry-meta -->

<p>Last time, we looked at <a href="/code/cancelling-a-windows-runtime-asynchronous-operation-part-3-c-cx-with-ppl-coroutine-style"> how task cancellation is projected in C++/CX with PPL and <code>co_await</code> with tasks</a>. But PPL also supports awaiting directly on <code>IAsyncAction^</code> and <code>IAsyncOperation^</code> objects. Let’s try it.</p>
<pre>auto picker = ref new FileOpenPicker();
picker-&gt;FileTypeFilter.Append(L".txt");

<span style="color: blue;">auto pickerOp = picker-&gt;PickSingleFileAsync();
cancellation_token_source cts;
call&lt;bool&gt; do_cancel([pickerOp](bool) { pickerOp.Cancel(); });
timer&lt;bool&gt; delayed_cancel(3000U, false, &amp;do_cancel);
delayed_cancel.start();</span>

StorageFile^ file;
try {
    file = co_await pickerOp;
} <span style="color: blue;">catch (OperationCanceledException^)</span> {
    file = nullptr;
}

if (file != nullptr) {
    DoSomething(file);
}
</pre>
<p>Observe that awaiting directly on an <code>IAsyncAction^</code> and <code>IAsyncOperation^</code> object throws a different exception from awaiting on a <code>task</code>.</p>
<p>You can see this in the <code>await_resume</code> for the <code>IAsyncInfo^</code> awaiter ind in <code>pplawait.h</code>:</p>
<pre>template &lt;typename _TaskTy, typename _HandlerTy&gt;
struct _IAsync_awaiter {
    ...

    auto await_resume() {
        <span style="color: blue;">_VerifyStateForResultsCall(_Task-&gt;Status);</span>
        return _Task-&gt;GetResults();
    }
};

void _VerifyStateForResultsCall(
    Windows::Foundation::AsyncStatus _Status)
{
    if (_Status == AsyncStatus::Canceled) {
        throw ::Platform::Exception::CreateException(E_ABORT);
    }
}
</pre>
<p>The PPL framework checks whether the status of the async operation is <code>Canceled</code>, and if so, it throws <code>E_ABORT</code>, which is represented in C++/CX as <code>Operation­Canceled­Exception</code>.</p>
<p>So far, all of the cancellation exceptions have generated by the framework. That’ll change soon. Next time, we’ll look at C++/WinRT.</p>


</body>